# Versioning System
HELIOS_BASE_VERSION = 1.0
HELIOS_CODENAME := Ten

# Set all versions
CUSTOM_BUILD_TYPE ?= UNOFFICIAL

CUSTOM_DATE_YEAR := $(shell date -u +%Y)
CUSTOM_DATE_MONTH := $(shell date -u +%m)
CUSTOM_DATE_DAY := $(shell date -u +%d)
CUSTOM_DATE_HOUR := $(shell date -u +%H)
CUSTOM_DATE_MINUTE := $(shell date -u +%M)
CUSTOM_BUILD_DATE_UTC := $(shell date -d '$(CUSTOM_DATE_YEAR)-$(CUSTOM_DATE_MONTH)-$(CUSTOM_DATE_DAY) $(CUSTOM_DATE_HOUR):$(CUSTOM_DATE_MINUTE) UTC' +%s)
CUSTOM_BUILD_DATE := $(CUSTOM_DATE_YEAR)$(CUSTOM_DATE_MONTH)$(CUSTOM_DATE_DAY)-$(CUSTOM_DATE_HOUR)$(CUSTOM_DATE_MINUTE)

CUSTOM_PLATFORM_VERSION := 10.0

TARGET_PRODUCT_SHORT := $(subst aosp_,,$(CUSTOM_BUILD))

HELIOS_VERSION := $(HELIOS_CODENAME)-v$(HELIOS_BASE_VERSION)-$(TARGET_PRODUCT_SHORT)-$(CUSTOM_BUILD_DATE)-$(CUSTOM_BUILD_TYPE)

CUSTOM_VERSION := Helios_$(HELIOS_BASE_VERSION)_$(CUSTOM_BUILD)-$(CUSTOM_PLATFORM_VERSION)-$(CUSTOM_BUILD_DATE)-$(CUSTOM_BUILD_TYPE)
CUSTOM_VERSION_PROP := 10

CUSTOM_PROPERTIES := \
    org.helios.version=$(HELIOS_VERSION) \
    org.helios.version.prop=$(CUSTOM_VERSION_PROP) \
    org.helios.version.display=$(CUSTOM_VERSION) \
    org.helios.build_version=$(HELIOS_BASE_VERSION) \
    org.helios.build_date=$(CUSTOM_BUILD_DATE) \
    org.helios.build_date_utc=$(CUSTOM_BUILD_DATE_UTC) \
    org.helios.build_type=$(CUSTOM_BUILD_TYPE) \
    org.helios.build_codename=$(HELIOS_CODENAME)

ifeq ($(CUSTOM_BUILD_TYPE), OFFICIAL)
PRODUCT_DEFAULT_DEV_CERTIFICATE := vendor/secure/releasekey
endif
